services:
  - type: web
    name: servidor-chat
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    rootDir: .
    
    envVars:
      - key: PORT
        value: 5001

      - key: FIREBASE_PROJECT_ID
        value: iglu-2025

      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@iglu-2025.iam.gserviceaccount.com

      - key: FIREBASE_PRIVATE_KEY
        value: |
          -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCFJGUiIm0ujUVq\nd8SM9YtdPORZist7K4YrRvSjdVs7dQNd0Mo59ogDF3b+Ct1uDu8AMfrU1sP/ldqI\n...rest-of-key...\n-----END PRIVATE KEY-----\n
